version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-app-name
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/market
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass

  mysql:
    image: mysql:8.0
    container_name: mysql_1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: market
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 5
    volumes:
      - ./mysql:/var/lib/mysql  # Здесь определен Docker-том для сохранения данных MySQL

